name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run type-check
        run: npm run type-check

      - name: Build project
        run: npm run build-only

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # Ensure the gh-pages branch starts cleanly
